employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index')
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee/models.py
from django.db import models
from django.utils import timezone


class Department(models.Model):
  name = models.CharField('部署名', max_length = 20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
    return self.name


class Club(models.Model):
  name = models.CharField('部活名', max_length = 20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
    return self.name


class Employee(models.Model):
  first_name = models.CharField('名', max_length = 20)
  last_name = models.CharField('姓', max_length = 20)
  email = models.EmailField('メールアドレス', blank = True)
  department = models.ForeignKey(
    Department, verbose_name = '部署', on_delete = models.PROTECT,
  )
  club = models.ManyToManyField(
    Club, verbose_name = '部活',
  )
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
      return '{0} {1} {2}'.format(self.last_name, self.first_name, self.department)
  

employee/forms.py
from django import forms
from . models import Club, Department


class SearchForm(forms.Form):
  club = forms.ModelChoiceField(
    queryset = Club.objects, label = 'サークル', required = False)

  department = forms.ModelChoiceField(
    queryset = Department.objects, label = '部署', required = False)

employee/views.py
from django.views import generic
from .forms import SearchForm
from .models import Employee


class IndexView(generic.ListView):
  model = Employee
  paginate_by = 1

  def get_context_data(self):
    context = super().get_context_data()
    context['form'] = SearchForm(self.request.GET)
    return context
  
  def get_queryset(self):
    form = SearchForm(self.request.GET)
    form.is_valid()

    queryset = super().get_queryset()

    department = form.cleaned_data['department']
    if department:
      queryset = queryset.filter(department = department)
    
    club = form.cleaned_data['club']
    if club:
      queryset = queryset.filter(club = club)
    return queryset
  

employee/templates/employee/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>社員管理システム</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">社員管理システム</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'employee:index' %}">一覧</a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:employee_employee_add' %}">社員追加</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

employee/templates/employee/employee_list.html
{% extends 'employee/base.html' %}

{% block content %}
<form action="" method="GET">
{{ form }}
<button type="submit">検索</button>
</form>


<table class="table table-bordered mt-4">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓</th>
      <th>名</th>
      <th>メール</th>
      <th>部署</th>
      <th>部活</th>
    </tr>
  </thead>
  <tbody>
  {% for employee in employee_list %}
  <tr>
    <td>{{ employee.pk }}</td>
    <td>{{ employee.last_name }}</td>
    <td>{{ employee.first_name }}</td>
    <td>{{ employee.email }}</td>
    <td>{{ employee.department }}</td>
    <td>{% for club in employee.club.all %}{{ club }}, {% endfor %}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include 'employee/page5.html' %}
{% endblock %}

employee/templates/employee/page4.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

employee/templates/employee/page5.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>